spring:
  application:
    name: library-layered-monolith
  mvc:
    problemdetails:
      enabled: true
  messages:
    basename: messages
  datasource:
    username: ${DB_USERNAME:library}
    password: ${DB_PASSWORD:library}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/library}
  flyway:
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
