spring:
  application:
    name: catalog-service
  docker:
    compose:
      file: ../compose.yaml
      lifecycle-management: start-only
  mvc:
    problemdetails:
      enabled: true
  messages:
    basename: messages
  datasource:
    username: ${DB_USERNAME:library}
    password: ${DB_PASSWORD:library}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/catalog_service}
  flyway:
    locations: classpath:db/migration

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
